/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Presentacion;

import Capa_Conexion.ConexionMySQL;
import Capa_Datos.PacienteDAO;
import Entidades.Paciente;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leo_v
 */
public class FrmPacientes extends javax.swing.JFrame {
ConexionMySQL conexionMySQL;
    Connection con;

    /**
     * Creates new form FrmPacientes
     */
    public FrmPacientes() {
        initComponents();
                conexionMySQL = new ConexionMySQL();
        con = conexionMySQL.conexion(); // Inicializar la conexión
     listarPacientes(); 
      cargarGerencias();
        cargarCondicionLaboral();
        cargarSeguro();
    }

    
   
 

    private void listarPacientes() {
    DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
    modelo.setRowCount(0); // Limpiar la tabla antes de listar

    ConexionMySQL conexionMySQL = new ConexionMySQL();
    Connection cn = conexionMySQL.conexion();

    try {
        CallableStatement cts = cn.prepareCall("call listar_pacientes()");
        ResultSet rs = cts.executeQuery();

        while (rs.next()) {
            Object[] fila = new Object[11];
            fila[0] = rs.getInt("id_paciente");
            fila[1] = rs.getString("nomape");
            fila[2] = rs.getString("dni");
            fila[3] = rs.getString("telefono");
            fila[4] = rs.getString("email");
            fila[5] = rs.getString("direccion");
            fila[6] = rs.getString("gerenciapa");
            fila[7] = rs.getString("conlaboralpa");
            fila[8] = rs.getString("diagnostico");
            fila[9] = rs.getString("seguropa");
            fila[10] = rs.getDate("fecha_nac");

            modelo.addRow(fila);
        }

    } catch (SQLException e) {
        System.out.println("Error al listar pacientes: " + e.getMessage());
    } finally {
        try {
            if (cn != null) {
                cn.close();
            }
        } catch (SQLException e) {
            System.out.println("Error al cerrar conexión: " + e.getMessage());
        }
    
    }
    }

    private void cargarGerencias() {
        cboGerencia.addItem("Seleccione Gerencia");
        cboGerencia.addItem("Personal");
        cboGerencia.addItem("Seguridad Ciudadana");
        cboGerencia.addItem("Desarrollo Social");
        cboGerencia.addItem("Procuraduría Pública");
        cboGerencia.addItem("Servicio de Administración Tributaria");
    }

    private void cargarCondicionLaboral() {
        cboCondicionLaboral.addItem("Seleccione Condición Laboral");
        cboCondicionLaboral.addItem("Tercero");
        cboCondicionLaboral.addItem("CAS");
        cboCondicionLaboral.addItem("Obrero");
        cboCondicionLaboral.addItem("Contratado");
        cboCondicionLaboral.addItem("Nombrado");
    }

    private void cargarSeguro() {
        cboSeguro.addItem("Seleccione Seguro");
        cboSeguro.addItem("SIS");
        cboSeguro.addItem("ESSALUD");
        cboSeguro.addItem("Privado");
    }

    private void limpiarCampos() {
        txtIdPaciente.setText("");
        txtNomApe.setText("");
        txtDNI.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        txtDireccion.setText("");
        cboGerencia.setSelectedIndex(0);
        cboCondicionLaboral.setSelectedIndex(0);
        txtDiagnostico.setText("");
        cboSeguro.setSelectedIndex(0);
        txtFechaNac.setText("");
        txtFechaNacS.setText("");
                }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        txtIdPaciente = new javax.swing.JTextField();
        txtNomApe = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        cboGerencia = new javax.swing.JComboBox<>();
        cboSeguro = new javax.swing.JComboBox<>();
        cboCondicionLaboral = new javax.swing.JComboBox<>();
        txtFechaNacS = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre y Apellido");

        jLabel2.setText("Codigo");

        jLabel3.setText("DNI");

        jLabel4.setText("Telefono");

        jLabel5.setText("Correo Electronico");

        jLabel6.setText("Direccion");

        jLabel7.setText("Condicion Laboral");

        jLabel8.setText("Gerencia");

        jLabel9.setText("Seguro");

        jLabel10.setText("Fecha de nacimiento");

        jLabel11.setText("Diagnostico");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre y apellido", "DNI", "Telefono", "Correo", "Direccion", "Gerencia", "Condicion Laboral", "Seguro", "Fecha nacimiento", "Fecha Segundo", "Diagnostico"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        txtFechaNacS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacSActionPerformed(evt);
            }
        });

        jLabel12.setText("Fecha y Segundos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaNac)
                            .addComponent(txtDireccion)
                            .addComponent(txtEmail)
                            .addComponent(txtTelefono)
                            .addComponent(txtDNI)
                            .addComponent(txtNomApe)
                            .addComponent(txtIdPaciente)
                            .addComponent(cboGerencia, 0, 232, Short.MAX_VALUE)
                            .addComponent(cboSeguro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboCondicionLaboral, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaNacS, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNomApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(jLabel4))
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboCondicionLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaNacS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar)
                    .addComponent(btnNuevo))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
           
    String nomApe = txtNomApe.getText();
    String dni = txtDNI.getText();
    String telefono = txtTelefono.getText();
    String email = txtEmail.getText();
    String direccion = txtDireccion.getText();
    String gerencia = cboGerencia.getSelectedItem().toString();
    String condicionLaboral = cboCondicionLaboral.getSelectedItem().toString();
    String diagnostico = txtDiagnostico.getText();
    String seguro = cboSeguro.getSelectedItem().toString();
    Date fechaNac = Date.valueOf(txtFechaNac.getText());
    Timestamp fechaRegistro = Timestamp.valueOf(txtFechaNacS.getText());

    // Crear un objeto Paciente
    Paciente paciente = new Paciente(0, nomApe, dni, telefono, email, direccion, gerencia, condicionLaboral, diagnostico, seguro, fechaNac, fechaRegistro);

    // Llamar al método de la capa de negocio para agregar un nuevo paciente
    PacienteDAO pacienteDAO = new PacienteDAO();
    String mensaje = pacienteDAO.registrarPaciente(con, paciente);

    // Mostrar mensaje de resultado
    JOptionPane.showMessageDialog(this, mensaje);

    // Actualizar la tabla de datos
    listarPacientes();

    // Limpiar los campos de texto después de agregar el paciente
    limpiarCampos(); 
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        {
    int idPaciente = Integer.parseInt(txtIdPaciente.getText());
    // Obtener los valores actualizados de los campos de texto
    String nomApe = txtNomApe.getText();
    String dni = txtDNI.getText();
    String telefono = txtTelefono.getText();
    String email = txtEmail.getText();
    String direccion = txtDireccion.getText();
    String gerencia = cboGerencia.getSelectedItem().toString();
    String condicionLaboral = cboCondicionLaboral.getSelectedItem().toString();
    String diagnostico = txtDiagnostico.getText();
    String seguro = cboSeguro.getSelectedItem().toString();
    Date fechaNac = Date.valueOf(txtFechaNac.getText());
    Timestamp fechaRegistro = Timestamp.valueOf(txtFechaNacS.getText());

    // Crear un objeto Paciente
    Paciente paciente = new Paciente(idPaciente, nomApe, dni, telefono, email, direccion, gerencia, condicionLaboral, diagnostico, seguro, fechaNac, fechaRegistro);

    // Llamar al método de la capa de negocio para actualizar el paciente
    PacienteDAO pacienteDAO = new PacienteDAO();
    String mensaje = pacienteDAO.actualizarPaciente(con, paciente);

    // Mostrar mensaje de resultado
    JOptionPane.showMessageDialog(this, mensaje);

    // Actualizar la tabla de datos
    listarPacientes();

    // Limpiar los campos de texto después de actualizar el paciente
    limpiarCampos();
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         int idPaciente = Integer.parseInt(txtIdPaciente.getText());

    // Llamar al método de la capa de negocio para eliminar el paciente
    PacienteDAO pacienteDAO = new PacienteDAO();
    String mensaje = pacienteDAO.eliminarPaciente(con, idPaciente);

    // Mostrar mensaje de resultado
    JOptionPane.showMessageDialog(this, mensaje);

    // Actualizar la tabla de datos
    listarPacientes();

    // Limpiar los campos de texto después de eliminar el paciente
    limpiarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
            limpiarCampos();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tblDatos.getSelectedRow();
    // Verificamos si se ha seleccionado alguna fila
    if (filaSeleccionada >= 0) {
        // Obtenemos los valores de las columnas de la fila seleccionada
        String idPaciente = tblDatos.getValueAt(filaSeleccionada, 0).toString();
        String nomApe = tblDatos.getValueAt(filaSeleccionada, 1).toString();
        String dni = tblDatos.getValueAt(filaSeleccionada, 2).toString();
        String telefono = tblDatos.getValueAt(filaSeleccionada, 3).toString();
        String email = tblDatos.getValueAt(filaSeleccionada, 4).toString();
        String direccion = tblDatos.getValueAt(filaSeleccionada, 5).toString();
        String gerencia = tblDatos.getValueAt(filaSeleccionada, 6).toString();
        String condicionLaboral = tblDatos.getValueAt(filaSeleccionada, 7).toString();
        String diagnostico = tblDatos.getValueAt(filaSeleccionada, 8).toString();
        String seguro = tblDatos.getValueAt(filaSeleccionada, 9).toString();
        String fechaNac = tblDatos.getValueAt(filaSeleccionada, 10).toString();
        String  fechaRegistro = tblDatos.getValueAt(filaSeleccionada,11).toString();


        // Asignamos los valores a los campos de texto correspondientes
        txtIdPaciente.setText(idPaciente);
        txtNomApe.setText(nomApe);
        txtDNI.setText(dni);
        txtTelefono.setText(telefono);
        txtEmail.setText(email);
        txtDireccion.setText(direccion);
        cboGerencia.setSelectedItem(gerencia);
        cboCondicionLaboral.setSelectedItem(condicionLaboral);
        txtDiagnostico.setText(diagnostico);
        cboSeguro.setSelectedItem(seguro);
        txtFechaNac.setText(fechaNac);
        txtFechaNacS.setText(fechaRegistro);

    }
    }//GEN-LAST:event_tblDatosMouseClicked

    private void txtFechaNacSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboCondicionLaboral;
    private javax.swing.JComboBox<String> cboGerencia;
    private javax.swing.JComboBox<String> cboSeguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtFechaNacS;
    private javax.swing.JTextField txtIdPaciente;
    private javax.swing.JTextField txtNomApe;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
